apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: venkeyboda/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          env:                   
            - name: REACT_APP_API_URL
              value: "http://backend-service:5000" 
