name: Docker Image Build and Push

on:
    push:
      branches:
        - main
jobs:

    build-push-scan:
        runs-on: ubuntu-latest

        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        steps:

            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Login to DockerHub
              run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            - name: Build Backend Image
              run: docker build -t $DOCKER_USERNAME/backend:latest ./backend

            - name: Build Frontend Image
              run: docker build -t $DOCKER_USERNAME/frontend:latest ./frontend

            - name: Push Backend Image
              run: docker push $DOCKER_USERNAME/backend:latest

            - name: Push Frontend Image
              run: docker push $DOCKER_USERNAME/frontend:latest 

            - name: Install Trivy
              run: |
                    wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.69.3_Linux-64bit.deb
                    sudo dpkg -i trivy_0.69.3_Linux-64bit.deb

            - name: Trivy scan Backend
              run: trivy image -f table $DOCKER_USERNAME/backend:latest > trivy-report.txt
                  
            - name: Trivy scan Frontend
              run: trivy image -f table $DOCKER_USERNAME/frontend:latest >> trivy-report.txt
